# Generated by Django 4.2.1 on 2023-06-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movements',
            name='value_mov',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
