# Generated by Django 4.2.1 on 2023-06-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accouts', '0004_movements_account_mov_movements_type_mov'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='activation_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
